#!/bin/bash

xset -display ":0" r rate 300 80
betterlockscreen -w

kill -HUP "$(pgrep dunst)" # Restart dunst since it ends up being in a wierd place.
notify-send -u normal "autorandr" "castor.laptop detected"
