alias t='timekeeper'
alias ll='exa -lhg --extended --git'
alias tksync='envdo aws/storage.ssly.se.gpg timekeeper-sync'
alias mic-check='arecord -vvv -f dat /dev/null'
alias tle='exa -T -a --git-ignore -I .git'
