alias t='timekeeper'
alias ll='exa -lhg --extended --git'
alias tksync='envdo aws/storage.ssly.se.gpg timekeeper-sync'
alias mic-check='arecord -vvv -f dat /dev/null'
alias tle='exa -T -a --git-ignore -I .git'
alias mysqlc='docker run -it --rm mysql mysql'
alias psqlc='docker run -it --rm postgres psql'
alias azure="docker run -v ${HOME}/.ssh:/root/.ssh -v ${HOME}/.azure:/root/.azure -it --rm microsoft/azure-cli azure"
alias az="docker run -v ${HOME}/.ssh:/root/.ssh -v ${HOME}/.azure:/root/.azure -v ${HOME}/.kube:/root/.kube -it --rm antonlindstrom/azure-cli"
alias gofindme="ngp -t go -I vendor"
alias e="$EDITOR -p"
